### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by tuxedlinux** [Abb1x/Tux#7]
Hi Abb1x,
I have found a spelling mistake whenever a member tries to run an administrator command without privileges.

The link for that spelling mistake is here: https://discord.com/channels/711643709095018527/711643709753655350/751347586597912637

The correction is : "@tuxedlinux is not in the sudoers file. This incident will be reported."

**Comment by Abb1x** [comment]
Hey! Thank you for reporting an issue, Where is the error exactly? ![Screenshot_20200906-151915.png](https://user-images.githubusercontent.com/54687179/92333559-6e7fa680-f054-11ea-807d-16806e213786.png)

**Comment by tuxedlinux** [comment]
> Hey! Thanks for reporting an issue, Where is the error exactly? ![Screenshot_20200906-151915.png](https://user-images.githubusercontent.com/54687179/92333559-6e7fa680-f054-11ea-807d-16806e213786.png)

The issue is where there is no space in the start of "This incident will be reported"

**Comment by Abb1x** [comment]
> > Hey! Thanks for reporting an issue, Where is the error exactly? ![Screenshot_20200906-151915.png](https://user-images.githubusercontent.com/54687179/92333559-6e7fa680-f054-11ea-807d-16806e213786.png)
> 
> The issue is where there is no space in the start of "This incident will be reported"

Alright, Thanks! Gonna fix in the next update

**Comment by tuxedlinux** [comment]
Ok, thanks! I will close this issue, I guess.
